### ISSUE TITLE
Where to find panel json

### ISSUE THREAD

**Issue by DavyCats** [hartwigmedical/peach#2]
I'm trying to run peach using the panel json provided here: https://nextcloud.hartwigmedicalfoundation.nl/s/LTiKTd8XxBqwaiC?path=%2FHMFTools-Resources%2FPeach%2F37 This however results in the below error. The 'chromosomeV37' key indeed appears to be missing in this panel json. Is there a panel json available somewhere which works with version 1.5?

```
2022-02-15 13:23:17 - [INFO    ] - Creating panel config from JSON
Traceback (most recent call last):
  File "/usr/local/share/peach/src/main.py", line 93, in <module>
    main(config)
  File "/usr/local/share/peach/src/main.py", line 31, in main
    panel = load_panel(tool_config.panel_path)
  File "/usr/local/share/peach/src/main.py", line 63, in load_panel
    return JsonParser().get_panel(json.load(json_file))
  File "/usr/local/share/peach/src/json_parser.py", line 60, in get_panel
    gene_infos = frozenset({self.get_gene_info(gene_info_json) for gene_info_json in data[self.GENES_KEY]})
  File "/usr/local/share/peach/src/json_parser.py", line 60, in <setcomp>
    gene_infos = frozenset({self.get_gene_info(gene_info_json) for gene_info_json in data[self.GENES_KEY]})
  File "/usr/local/share/peach/src/json_parser.py", line 65, in get_gene_info
    chromosome_v37 = str(data[self.CHROMOSOME_V37])
KeyError: 'chromosomeV37'
```

**Comment by DFKoetsier** [comment]
Apologies for the slow response. That JSON was indeed out of date. I have just uploaded the most recent version.

**Comment by DavyCats** [comment]
Thanks!
